name: "pagely-deploy-nonprod"
on:
  push:
    branches:
      - 'nonprod'
jobs:
  deploy:
    name: Deploy to Pagely (non-production)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "mjPTTw37xByacb9nTmT3D7"
          PAGELY_APP_ID: "44884"
          PAGELY_WORKING_DIR: ${{github.workspace}}
