name: "pagely-deploy-prod"
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: Deploy to Pagely (production site)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run deploy
        uses: godaddy-wordpress/pagely-deploy-action@v1
        with:
          PAGELY_DEPLOY_DEST: "/httpdocs"
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_INTEGRATION_SECRET}}
          PAGELY_INTEGRATION_ID: "GauH5ERGqDF3gGdnNCXTwJ"
          PAGELY_APP_ID: "45800"
          PAGELY_WORKING_DIR: ${{github.workspace}}
